sudo: required

# really, we're node but want to skip the implict npm install on the host 
# which is not needed when using docker
language: python

services:
    - docker

script:
    - make test integration-test

notifications:
  email:
    on_success: change
    on_failure: always
  slack: cloudet:rMfRKhvsbZuCIRZpTct3kBI4
